dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
      - libboost-test-dev
      - libspdlog-dev
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -v https://yandex.ru/internet/
#    - curl -f -T cmake-0.0.0$TRAVIS_BUILD_NUMBER-Linux.deb -upuffikru:$BINARY_API_KEY "https://api.bintray.com/content/puffikru/otus-cpp/otus-cpp/$TRAVIS_BUILD_NUMBER/cmake-0.0.0$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"